import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';

export default function Home() {
  const [posts, setPosts] = useState('');
  useEffect(() => {
    getPosts();
  }, []);

  const getPosts = async () => {
    const posts = await axios.get(
      'https://express-multer-r2-production.up.railway.app/'
    );

    // setMessage(new URL(message.data));
    setPosts(posts.data);
  };

  console.log(posts);

  return (
    <div className=" w-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts &&
          posts.map((post) => (
            <div key={post.id}>
              <Image
                src={post.imageName}
                alt="Picture of the author"
                width="430px"
                height={768}
              ></Image>
              <p> {post.caption}</p>
            </div>
          ))}
      </div>
    </div>
  );
}
