import axios from 'axios';
import Head from 'next/head';
import { useEffect, useState } from 'react';

export default function Home() {
  const [message, setMessage] = useState();
  useEffect(() => {
    getMessage();
  }, []);

  const getMessage = async () => {
    const message = await axios.get('http://localhost:8888');

    setMessage(JSON.stringify(message.data));
  };

  return (
    <div className="h-screen w-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Multer-r2-FE</h1>
        {message && <pre>{message}</pre>}
      </div>
    </div>
  );
}
