import Head from 'next/head';

import axios from 'axios';
import { useState } from 'react';

const NewPost = () => {
  const [file, setFile] = useState();
  const [caption, setCaption] = useState('');
  const submit = async (event) => {
    event.preventDefault();

    const formData = new FormData();
    formData.append('image', file);
    formData.append('caption', caption);
    await axios.post('http://localhost:8888/upload', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
  };

  const fileSelected = (event) => {
    const file = event.target.files[0];
    setFile(file);
  };
  return (
    <div className="h-screen w-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form
          onSubmit={submit}
          style={{ width: 650 }}
          className="flex flex-col space-y-5 px-5 py-14"
        >
          <input onChange={fileSelected} type="file" accept="image/*"></input>
          <input
            value={caption}
            onChange={(e) => setCaption(e.target.value)}
            type="text"
            placeholder="Caption"
          ></input>
          <button type="submit">Submit</button>
        </form>
      </div>
    </div>
  );
};

export default NewPost;
